sudo: required

services:
  - docker
  
before_install:
  - docker pull debian:10.6

after_success:
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh -O u.sh
  - chmod a+x ./u.sh
  - ./u.sh release/*

script:
  - docker run --rm -v $(pwd)/:/build/ -w /build/ debian:10.6 bash build.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
