#!/bin/sh
HERE=$(dirname $(readlink -f "${0}"))
#sed -i -e 's|././|/usr|g' ./usr/lib/x86_64-linux-gnu/libgtk-3.so.0
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"
export LD_PRELOAD="${HERE}/usr/lib/vlc/plugins/gui/libskins2_plugin.so"
export LD_PRELOAD="${HERE}/usr/lib/vlc/plugins/audio_output/libjack_plugin.so"
export LD_PRELOAD="${HERE}/usr/lib/vlc/plugins/access/libaccess_jack_plugin.so"
export LD_PRELOAD="${HERE}/usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0"
export LD_PRELOAD="${HERE}/usr/lib/x86_64-linux-gnu/libQt5Core.so.5"
export LD_PRELOAD="${HERE}/usr/lib/vlc/plugins/gui/libncurses_plugin.so"
export LD_PRELOAD="${HERE}/usr/lib/vlc/plugins/access/libpulsesrc_plugin.so"
export LD_PRELOAD="${HERE}/usr/lib/vlc/plugins/services_discovery/libpulselist_plugin.so"
#export LD_PRELOAD="${HERE}/usr/lib/x86_64-linux-gnu/libpcre2-16.so.0.3.0"
#export LD_PRELOAD="${HERE}/usr/lib/x86_64-linux-gnu/libpcre2-16.so.0"
#export QT_QPA_PLATFORMTHEME="gtk3"
#export QT_QPA_PLATFORMTHEME="qt5ct"
#export QT_DEBUG_PLUGINS=1
export FONTCONFIG_PATH="${HERE}"/etc/fonts/:"${FONTCONFIG_PATH}"
export VLC_PLUGINS_PATH="${HERE}"/usr/lib/vlc/plugins/:"${VLC_PLUGINS_PATH}"
export QTPATH=/usr/lib/x86_64-linux-gnu/qt5/bin/:"${QTPATH}"
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib32/:"${HERE}"/lib64/:"${LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${PYTHONPATH}"
export PYTHONHOME="${HERE}"/usr/
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
export PERLLIB="${HERE}"/usr/share/perl5/:"${HERE}"/usr/lib/perl5/:"${PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
export LD_LIBRARY_PATH="${HERE}"/usr/sbin:"${HERE}"/usr/bin/:"${HERE}"/sbin/:"${HERE}"/bin/:"${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${HERE}"/usr/lib/x86_64-linux-gnu/mesa:"${HERE}"/usr/lib/x86_64-linux-gnu/mesa-egl/:"${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib:"${HERE}"/usr/lib/vlc/:"${HERE}"/usr/lib/x86_64-linux-gnu:"${HERE}"/usr/lib/x86_64-linux-gnu/mesa:"${HERE}"/usr/lib/x86_64-linux-gnu/mesa-egl/:"${HERE}"/usr/lib/x86_64-linux-gnu/pulseaudio/:"${HERE}"/usr/lib/x86_64-linux-gnu/samba/:"${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${HERE}"_LIBRARY_PATH:$LD_LIBRARY_PATH
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
exec ${EXEC} $@
